### PR TITLE
18517 Mock examine store

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #18517:*

*Description of changes:*

Part of the Vue 3 upgrade.

This PR implements a mock examine store and connects the Vue components to use it.

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1423-vgzxlv6j.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1423-vgzxlv6j.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1423-vgzxlv6j.web.app

**Review by rarmitag — APPROVED** [review]

**Pull request merged**
