### PR TITLE
20343 Fix alt + E shortcut opening browser settings

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #:*
bcgov/entity#20343

*Description of changes:*
This PR prevents the default browser actions from firing when a mnemonic shortcut is pressed.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1442-jkgqrrxj.web.app

**Review by stevenc987 — APPROVED** [review]

**Comment by eve-git** [comment]
The version needs to be updated to 1.2.11

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1442-jkgqrrxj.web.app

**Pull request merged**
