### PR TITLE
21295 Resolve NUXT Build Warning ProseCode

### PR DESCRIPTION
**Pull request by hanlunBCRegistries**
*Issue #:

*Description of changes:*
- Updated `@nuxt/content` to version `^2.8.2` in `package.json`.
- Updated `nuxt` to version `^3.7.2` in `package.json`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1505-j7mdkfls.web.app

**Comment by EPortman** [comment]
Could you bump up the version number in `package.json`.

**Comment by hanlunBCRegistries** [comment]
> Could you bump up the version number in `package.json`.

just updated

**Review by EPortman — APPROVED** [review]
Looks good.

**Pull request merged**
