### PR TITLE
#24298 Name-Examination UI - error occurred when selecting conflict or conflict selection has values

### PR DESCRIPTION
**Pull request by eve-git**
*Issue #:*
https://github.com/bcgov/entity/issues/24298

*Description of changes:*
This is an update to the previous code change: the section for retrieving conflict business info from Entities has been commented out because:
1. The corp number from Solr query result is in the COLIN format (without the BC prefix).
2. The business query does not provide office and party information.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1550-2v6nlstm.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1550-2v6nlstm.web.app

**Review by EPortman — APPROVED** [review]
LGTM

**Pull request merged**
