### PR TITLE
20341 Move save/cancel edit button to the bottom of the page

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #:*
bcgov/entity#20341

*Description of changes:*
This PR moves the save/cancel button in the edit view of the Examine page to the bottom of the screen.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1444-v11dt3xl.web.app

**Review by eve-git — APPROVED** [review]
LGTM. could you update the version umber in package-lock.json as well?

**Comment by semmatti** [comment]
> LGTM. could you update the version umber in package-lock.json as well?

thanks, updated

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1444-v11dt3xl.web.app

**Pull request merged**
