### PR TITLE
Fix: Allow Accordion Text Selection and Copy in Exact Word Order + Synonym Match 

### PR DESCRIPTION
**Pull request by shaangill025**
*Issue #:21000*

*Description of changes:*
Fixed the accordion text which was not drag selectable by setting `user-select: text` property in styles. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1453-jct141hm.web.app

**Review by eve-git — APPROVED** [review]

**Comment by eve-git** [comment]
Please update the version number in package.json and package-lock.json?

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1453-jct141hm.web.app

**Review by eve-git — APPROVED** [review]

**Pull request merged**
