### PR TITLE
22417 clean up smoke tests

### PR DESCRIPTION
**Pull request by EPortman**
*Issue #:*
- Removed Tests related to Name-Request (they have been moved to Name-Request repo).
- Updated the Priority Queue Toggle test to be more stable.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Review by eve-git — APPROVED** [review]
LGTM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Comment by EPortman** [comment]
No need to review / merge yet. Still trying to get Smoke Test working in Cloud Build. It is working locally but not in the cloud build.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1487-zqo9q84c.web.app

**Pull request merged**
