### PR TITLE
20335/20336 Fix keyboard navigation

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #:*
bcgov/entity#20335
bcgov/entity#20336

*Description of changes:*
This PR fixes some bugs introduced by PR #1440.
 - Fixed exact match conflicts not being able to be focused
 - Fixed clicking checkbox to select conflicts

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1441-sqks7zil.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1441-sqks7zil.web.app

**Review by rarmitag — APPROVED** [review]

**Pull request merged**
