### PR TITLE
Bug fixes part 1

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #:*
bcgov/entity#20018
bcgov/entity#20019
bcgov/entity#20005
bcgov/entity#19984
bcgov/entity#20009
bcgov/entity#19983
bcgov/entity#19980
bcgov/entity#19985
bcgov/entity#19978
bcgov/entity#19979
bcgov/entity#19981

*Description of changes:*
Part of the Vue 3 upgrade.
This PR implements bug fixes for the tickets listed above. In addition, some function names in the examine store were renamed, and error handling was added for recipe area loading.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1430-lxtfpbts.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1430-lxtfpbts.web.app

**Review by ozamani9gh — APPROVED** [review]

**Pull request merged**
