### PR TITLE
18246 Name Examination Page Templates

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #18246:*

*Description of changes:*

Part of the Vue 3 migration

This PR completes the HTML / CSS templates needed for the examination page in the new Name Examination UI.

Layout of the UI components should be fairly identical to the previous version.

Some notes:
Mock data has been used only to show how the components will look when populated with data, and the data itself may not be accurate / make sense with the rest of the page. In the Conflicts tab, only one bucket has been populated with data as this is enough to illustrate what the components will look like in the other buckets. Some data is hardcoded into templates and can be parameterized in a later ticket when introducing the mock / actual state stores.

Some basic logic has been implemented to show how the components / entire page switches between different states.

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1407-uo2zfl9x.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1407-uo2zfl9x.web.app

**Review by rarmitag — APPROVED** [review]

**Pull request merged**
