### PR TITLE
#24298 Ensure no errors occur even when conflict corp information is empty.

### PR DESCRIPTION
**Pull request by eve-git**
*Issue #:*
https://github.com/bcgov/entity/issues/24298

*Description of changes:*
Ensure no errors occur even when conflict corp information is empty

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1548-vs0w0hrz.web.app

**Review by EPortman — APPROVED** [review]
Confirmed no warnings / errors when selecting a conflict on the test URL. 

Looks great.

**Pull request merged**
