### PR TITLE
Fix requestor message clear button

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #:*
bcgov/entity#20287

*Description of changes:*
Fixes the clear button size when the requestor message is edited, and the reset button on the recipe search inputs.

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1436-zt7jf52j.web.app

**Review by rarmitag — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1436-zt7jf52j.web.app

**Pull request merged**
