### PR TITLE
Fix conflict list occasionally not appearing

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #:*
bcgov/entity#20304

*Description of changes:*
This PR adds a null check to the `jurisdiction` field in `ConflictListItem`, which can sometimes be `undefined`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1437-m2u8oqlq.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1437-m2u8oqlq.web.app

**Review by mengdong19 — APPROVED** [review]

**Pull request merged**
