### PR TITLE
Bug fixes part 4

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #:*
bcgov/entity#20204
bcgov/entity#20155
bcgov/entity#20233

*Description of changes:*
Part of the Vue 3 upgrade.
This PR fixes the previous implementation for bcgov/entity#20204 and bcgov/entity#20155. It also fixes bcgov/entity#20233.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1434-nqhv0qlp.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1434-nqhv0qlp.web.app

**Review by eve-git — APPROVED** [review]

**Pull request merged**
