### PR TITLE
20592 Fix recipe area scrolling too far when expanding list

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #:*
bcgov/entity#20592

*Description of changes:*
This PR fixes a bug where the recipe area sometimes scrolls too far when a conflict list is expanded.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1449-tfsw6cpz.web.app

**Review by eve-git — APPROVED** [review]
LGTM.
By the way, I noticed that many package versions have been updated in package-lock.json. Is this expected?

**Comment by semmatti** [comment]
> LGTM. By the way, I noticed that many package versions have been updated in package-lock.json. Is this expected?

Yes, it should be fine, I just deleted `node_modules` and `package-lock.json` and ran `npm install` again.

**Pull request merged**
