### PR TITLE
16934 Complete search page

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #16934:*

*Description of changes:*

Part of the Vue 3 migration, this PR:
- Fixes CSS and makes the name examination search page more responsive
- Implements custom submitted date ranges and the ordering of results by submitted date
- Adds HeadlessUI as a component library
- Replaces FontAwesome and svg-icon/mdi with HeroIcons
- Adds component tests using Vitest
- Converts the Pinia stores to use the composition API
- Refactors the codebase

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1401-pueb7d1m.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1401-hol0z4ob.web.app

**Review by rarmitag — APPROVED** [review]

**Review by eve-git — APPROVED** [review]

**Comment by rarmitag** [comment]
@ozamani9 -
Just a few observations. Need omid's opinion.

When filtering on Consent Required, when I choose Required, I still see a No.

When filtering on Submitted, the date doesn't order by date.

** Actually when veiewing the search page in general there is no order.

Not sure what the banner should say.

**Pull request merged**
