### PR TITLE
20297 create e2e smoke test

### PR DESCRIPTION
**Pull request by rstens**
*Issue #:* 20297

*Description of changes:*
First cut of the E2E smoke test built in Cypress:
* Cypress framework and configuration
* Links Smoke Test
* Check on Namex on navigation, examine, search and stats
* Addition of of various ```data-testid``` and ```id``` throughout the code to support testing
* adding ```.nuxtignore``` to avoid the cypress testing code when building

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by rstens** [comment]
Needs /gcbrun

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1466-o8yrksf2.web.app

**Review by EPortman — APPROVED** [review]
Looks great. 
Seems like a good idea to move application logic into an app/ src directory for ease of organization.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1466-o8yrksf2.web.app

**Pull request merged**
