### PR TITLE
Examination screen keyboard navigation

### PR DESCRIPTION
**Pull request by semmatti**
*Issue #:*
bcgov/entity#20335
bcgov/entity#20336

*Description of changes:*
This PR implements keyboard navigation for the Examine screen. Changes include:
- Pressing tab now cycles between recipe search inputs and the conflicts area when the conflicts tab is selected.
- Keyboard navigation implemented for the conflicts area.
   - up arrow/down arrow: focus the next/previous conflict
   - right arrow: expand the focused conflict
   - left arrow: collapse the focused conflict
   - space: select the focused conflict

Additionally, components in the conflicts tab were refactored.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1440-62j7a94i.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1440-62j7a94i.web.app

**Review by eve-git — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://namex-dev--pr-1440-62j7a94i.web.app

**Pull request merged**
